
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.undergarden]
			depthrock = true
			shiverstone = true
			tremblecrust = true

		[types.stone_type.tconstruct]
			seared_stone = true
			scorched_stone = true

		[types.stone_type.crusty_chunks]
			trinitite = true
			bauxite = true

		[types.stone_type.regions_unexplored]
			argillite = true
			chalk = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.naturalist]
			shellstone = true

	[types.wood_type]

		[types.wood_type.netherexp]
			claret = true
			smokestalk = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.tconstruct]
			greenheart = true
			skyroot = true
			bloodshroom = true
			enderbark = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = true
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

	[types.leaves_type]

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.tconstruct]
			earth_slime = true
			sky_slime = true
			ender_slime = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.regions_unexplored]
			alpha = true
			apple_oak = true
			bamboo = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			flowering = true
			golden_larch = true
			kapok = true
			larch = true
			maple = true
			mauve = true
			orange_maple = true
			palm = true
			pine = true
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = true
			ashen = true

		[types.leaves_type.upgrade_aquatic]
			river = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.handcrafted]
			corner_trim = true
			pillar_trim = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

		[entries.stone_type.mcwbridges]
			balustrade_bricks_bridge = true
			mossy_bridge_pier = true
			mossy_brick_bridge = true
			bridge_pier = true
			mossy_bridge_stair = true
			balustrade_mossy_bricks_bridge = true
			brick_bridge_stair = true
			bridge = true
			brick_bridge = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			nightstand = true
			cupboard = true
			dining_bench = true
			bench = true
			couch = true
			table = true
			chair = true
			drawer = true
			pillar_trim = true
			side_table = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.mcwbridges]
			log_bridge_stair = true
			rail_bridge = true
			bridge_pier = true
			rope_bridge = true
			rope_bridge_stair = true
			log_bridge_middle = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

