#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 25 21:01:32 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.7.1.zip
enableShaders=false
